name: dart_deta_frog_todo_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.2.0
  deta: ^0.0.3+1
  dio: ^4.0.6
  dio_client_deta_api: ^0.0.1
  dotenv: ^4.0.1
  logger: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
