name: cutie_todo_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^0.3.1
  dart_jsonwebtoken: ^2.5.0
  deta: ^0.0.3+1
  dio: ^4.0.6
  dio_client_deta_api: ^0.0.1
  dotenv: ^4.0.1
  get_it: ^7.2.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  tuple: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
