// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE6p-9bHsYvTZYXscdj2nDIdhh9EIzEfc',
    appId: '1:552028729796:web:d54764d269ff5fa7a6b491',
    messagingSenderId: '552028729796',
    projectId: 'cutie-todo',
    authDomain: 'cutie-todo.firebaseapp.com',
    storageBucket: 'cutie-todo.appspot.com',
    measurementId: 'G-VR93FE5QWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM9nGSw_VkO5QxrvwCn1lxC_5CdujSvjA',
    appId: '1:552028729796:android:9eaf87381208d65da6b491',
    messagingSenderId: '552028729796',
    projectId: 'cutie-todo',
    storageBucket: 'cutie-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa1M4TPzPDpnMdm-AmWd3F1NRD2RcxEPE',
    appId: '1:552028729796:ios:a87d7f924fc9e98fa6b491',
    messagingSenderId: '552028729796',
    projectId: 'cutie-todo',
    storageBucket: 'cutie-todo.appspot.com',
    iosClientId: '552028729796-sgbkfpgpmngtl7ibf3pmopco8l5r0mp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.cutie-todo-app',
  );
}
